# Generated by Django 2.1.5 on 2019-01-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anacreon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='sovID',
            field=models.PositiveIntegerField(default=4365595),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgamedata',
            name='sovID',
            field=models.PositiveIntegerField(default=4365595),
            preserve_default=False,
        ),
    ]
