# Generated by Django 2.1.5 on 2019-01-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anacreon', '0002_auto_20190110_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgamedata',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalGameData',
        ),
    ]
